"""migration.

Revision ID: b5a92e1c31f3
Revises: 73db8ccd4b49
Create Date: 2022-05-10 02:27:28.234100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a92e1c31f3'
down_revision = '73db8ccd4b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('comment_id', sa.Integer(), nullable=False))
    op.add_column('pitches', sa.Column('vote_id', sa.Integer(), nullable=False))
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pitches', 'votes', ['vote_id'], ['id'])
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'pitches', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'vote_id')
    op.drop_column('pitches', 'comment_id')
    # ### end Alembic commands ###
